Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty array (2x2):\n", empty_array)

# 2. Initialize an all-ones array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll ones array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
# Example: shape (3, 3), fill value = 7
filled_array = np.full((3, 3), 7)
print("\nArray filled with 7 (3x3):\n", filled_array)

# 4. Return a new array of zeros with same shape and type as a given array
example_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(example_array)
print("\nArray of zeros with same shape as example_array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(example_array)
print("\nArray of ones with same shape as example_array:\n", ones_like_array)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
converted_array = np.array(new_list)
print("\nConverted numpy array from list:\n", converted_array)


Empty array (2x2):
 [[4.86104841e-310 0.00000000e+000]
 [3.28097404e-085 6.55435014e-310]]

All ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Array of zeros with same shape as example_array:
 [[0 0]
 [0 0]]

Array of ones with same shape as example_array:
 [[1 1]
 [1 1]]

Converted numpy array from list:
 [1 2 3 4]


Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50)
print("Array ranging from 10 to 49:\n", array_range)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix with values from 0 to 8:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array of size 30:\n", random_array)
print("Mean of the array:", mean_value)

# 5. Create a 10x10 array with random values and find the min and max values
array = np.random.randint(0, 23, size=(10, 10))
print(array)
min_val = array.min()
max_val = array.max()
print("Minimum value:", min_val)
print("Maximum value:", max_val)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 corresponds to the 5th element
print("\nZero array with 5th element replaced by 1:\n", zero_array)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print("\nReversed array:\n", reversed_array)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with border 1 and inside 0:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill 1s in alternate cells starting from (1, 0)
checkerboard[::2, 1::2] = 1  # Fill 1s in alternate cells starting from (0, 1)
print("\n8x8 Checkerboard pattern:\n", checkerboard)


Array ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
 [0.16519598 0.64917889 0.90555403 0.42333916 0.75680518 0.64237855
 0.53815188 0.58769295 0.97538657 0.23138956 0.96313392 0.76748528
 0.80468288 0.5162975  0.25296946 0.85499246 0.8516017  0.56223526
 0.49640401 0.45657059 0.09894669 0.25794155 0.63584796 0.77711129
 0.41685773 0.17740801 0.83855488 0.11120128 0.56176392 0.80844623]
Mean of the array: 0.5695175114678738
[[ 1 19 10 11 16  6  9 13 10  5]
 [ 5 17  3 19  5 13 20  2 17  8]
 [ 5 10 13  4 17 18 10 22  0 17]
 [ 6 12 22 18 19  4  5  9  0 14]
 [20  6 17  2 13  7  5 20  5  4]
 [19  1 21  6 21  2 19 13 21 18]
 [ 5 11 15 11  5 11  0  7  3  8]
 [ 4  9 16  5 10  8 11  6  1 13]
 [ 9  9 17 17  9  2  1  9 17 20]
 [18  4 15  2  9 10 14 

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_arrays = x + y
print("1. Addition of x and y:\n", add_arrays)

# 2. Subtract the two arrays
subtract_arrays = x - y
print("\n2. Subtraction of x and y:\n", subtract_arrays)

# 3. Multiply the array `x` with an integer (e.g., 3)
multiply_array = x * 3
print("\n3. Multiplication of x with 3:\n", multiply_array)

# 4. Find the square of each element of `x`
square_array = x ** 2
print("\n4. Square of each element in x:\n", square_array)

# 5. Find the dot product
# Dot product of v and w
dot_product_vw = np.dot(v, w)
print("\n5a. Dot product of v and w:", dot_product_vw)

# Dot product of x and v
dot_product_xv = np.dot(x, v)
print("5b. Dot product of x and v:\n", dot_product_xv)

# Dot product of x and y
dot_product_xy = np.dot(x, y)
print("5c. Dot product of x and y:\n", dot_product_xy)

# 6. Concatenate x and y along rows; concatenate v and w along columns
concat_xy = np.concatenate((x, y), axis=0)  # Along rows
concat_vw = np.vstack((v, w))  # Vertically stacks v and w
print("\n6a. Concatenation of x and y along rows:\n", concat_xy)
print("6b. Concatenation of v and w along columns:\n", concat_vw)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\n7. Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\n7. Error during concatenation of x and v:")
    print(e)
    print("Explanation: `x` is a 2D array (shape 2x2), while `v` is a 1D array (shape 2). "
          "Their dimensions are incompatible for direct concatenation along the specified axis.")


1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]]

5a. Dot product of v and w: 219
5b. Dot product of x and v:
 [29 77]
5c. Dot product of x and y:
 [[19 22]
 [50 58]]

6a. Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

7. Error during concatenation of x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: `x` is a 2D array (shape 2x2), while `v` is a 1D array (shape 2). Their dimensions are incompatible for direct concatenation along the specified axis.


In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A^(-1) = I
A_inv = np.linalg.inv(A)  # Find inverse of A
identity_matrix = np.dot(A, A_inv)  # Multiply A with its inverse
print("1. A * A^(-1) = I:\n", identity_matrix)
print("Is A * A^(-1) equal to I?", np.allclose(identity_matrix, np.eye(2)))

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("Is AB equal to BA?", np.array_equal(AB, BA))  # AB != BA (in general for non-commutative matrices)

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)  # Transpose of AB
BT_AT = np.dot(B.T, A.T)  # Multiply transpose of B and A
print("\n3. (AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)
print("Is (AB)^T equal to B^T * A^T?", np.allclose(AB_T, BT_AT))


1. A * A^(-1) = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A * A^(-1) equal to I? True

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB equal to BA? False

3. (AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T * A^T? True


In [ ]:
# Coefficient matrix A
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

# Constant matrix B
B = np.array([-1, -3, 9])

# Solve for X using np.linalg.inv (inverse method)
A_inv = np.linalg.inv(A)  # Compute inverse of A
X = np.dot(A_inv, B)  # Solve for X using A_inv * B
print("\nSolution using inverse method:")
print("x, y, z =", X)
# Solve using np.linalg.solve (direct method, numerically stable)
X_solve = np.linalg.solve(A, B)
print("\nSolution using np.linalg.solve:")
print("x, y, z =", X_solve)



Solution using inverse method:
x, y, z = [ 2.  1. -2.]

Solution using np.linalg.solve:
x, y, z = [ 2.  1. -2.]
